### ISSUE TITLE
Light client usage documentation

### ISSUE THREAD

**Issue by k06a** [sorpaas/rust-ethash#1]
Is there any doc for light client usage? Gonna use it in NEAR smart contracts, compiled to WebAssembly: https://github.com/nearprotocol/near-bridge

**Comment by Rizziepit** [comment]
I'm also interested in light client usage. @k06a were you able to use this? Any code pointers for usage?

**Comment by k06a** [comment]
> I'm also interested in light client usage. @k06a were you able to use this? Any code pointers for usage?

Hi, I used merkelized roots of bunch of a DAG files: https://github.com/near/rainbow-bridge/blob/master/contracts/near/eth-client/src/lib.rs#L382
